services:

  db:
    image: postgres:15-alpine
    container_name: vetai_db
    restart: always
    env_file:
      - backend/.env
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vetai-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: vetai_backend
    restart: always
    env_file:
      - backend/.env
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - vetai-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vetai_frontend
    restart: always
    env_file:
      - backend/.env
    expose:
      - "3000"
    networks:
      - vetai-network
      - red-proxy

volumes:
  postgres_data:

networks:
  vetai-network:
    driver: bridge

  red-proxy:
    external: true